### ISSUE TITLE
Header Text is hard to read

### ISSUE THREAD

**Issue by M-Naveed-Ashraf** [codelover1226/Union-building#1]
<img width="1723" alt="Screenshot 2024-10-27 at 9 43 24 PM" src="https://github.com/user-attachments/assets/f9d6ba61-ddd8-4f8d-a52b-280a4a940a87">

**Comment by SpasiboKojima** [comment]
Do not run any code from this person:
https://github.com/codelover1226/Union-building/blob/main/middleware/config.js

**Comment by M-Naveed-Ashraf** [comment]
Thankfully, I didn't run it locally, I just checked the deployed version of it.
